rvm:
  - 2.1
  - 2.0.0
  - 1.9.3
services: mongodb
script:
 - bundle exec rubocop
 - bundle exec rake
env:
  - "RAILS_VERSION=3.2.21"
  - "RAILS_VERSION=4.0.12"
  - "RAILS_VERSION=4.1.8"
  - "RAILS_VERSION=4.2.0"
